//
// Created by Jessie Mejia on 3/15/23.
//

#ifndef TEXTINPUTPROJECT_FONTSENUM_H
#define TEXTINPUTPROJECT_FONTSENUM_H

enum fontsEnum{
    BEBAS,
    SUNFLOWER,
    TALLFILM,
    LAST_FONT
};

#endif //TEXTINPUTPROJECT_FONTSENUM_H
