//
// Created by Jessie Mejia on 3/18/23.
//

#ifndef TEXTINPUTPROJECT_STATESENUM_H
#define TEXTINPUTPROJECT_STATESENUM_H

enum StatesEnum {
    HIDDEN,
    LAST_STATE
};

#endif //TEXTINPUTPROJECT_STATESENUM_H
