//
// Created by Jessie Mejia on 5/3/23.
//

#ifndef MUSICPLAYERTEST_TEXTUREENUMS_H
#define MUSICPLAYERTEST_TEXTUREENUMS_H

enum TextureEnums
{
    KODAKBLACK_INSTITUTION,
    LILUZIVERT_LUVISRAGE,
    TPLT,
    ENDLESS,

    PLAY,
    PAUSE,
    NEXT,
    HEART,
    HEART_FILL,
    PLAYCIRCLE,
    PAUSECIRCLE,
    LAST_TEXTURE
};
#endif //MUSICPLAYERTEST_TEXTUREENUMS_H
